### ISSUE TITLE
Simple ClassNotFoundException

### ISSUE THREAD

**Issue by lidox** [fenjuly/ToggleExpandLayout#13]
#### My layout.xml looks like this: 
`

      <com.fenjuly.mylibrary.ToggleExpandLayout
            android:id="@+id/toogleLayout1"
            android:layout_marginTop="15dp"
            android:layout_marginLeft="15dp"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            >

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                >
                <TextView
                    android:id="@+id/menu"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:layout_marginLeft="8dp"
                    android:text="Automatic date and time"
                    />
                <TextView
                    android:layout_below="@+id/menu"
                    android:layout_marginTop="4dp"
                    android:layout_marginLeft="8dp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Use network provide time"
                    android:textColor="#cccccc"/>
                <com.kyleduo.switchbutton.SwitchButton
                    android:id="@+id/switch_button"
                    android:layout_alignParentRight="true"
                    android:layout_marginRight="10dp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:padding="16dp"/>
            </RelativeLayout>

        </com.fenjuly.mylibrary.ToggleExpandLayout>

    </com.fenjuly.mylibrary.DropDownLayout>
`

### Trace:
`
FATAL EXCEPTION: main
                                                                    Process: com.artursworld.nccn, PID: 2427
                                                                    android.view.InflateException: Binary XML file line #37: Binary XML file line #37: Error inflating class com.fenjuly.mylibrary.DropDownLayout
                                                                    Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class com.fenjuly.mylibrary.DropDownLayout
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.fenjuly.mylibrary.DropDownLayout" on path: DexPathList[[zip file "/data/app/com.artursworld.nccn-2/base.apk"],nativeLibraryDirectories=[/data/app/com.artursworld.nccn-2/lib/x86, /system/lib, /vendor/lib]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:609)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                        at com.afollestad.materialdialogs.MaterialDialog$Builder.customView(MaterialDialog.java:1068)
                                                                        at com.artursworld.nccn.view.user.UserStartConfiguration.showConfigurationDialog(UserStartConfiguration.java:29)
                                                                        at com.artursworld.nccn.view.StartMenu.onNavigationItemSelected(StartMenu.java:55)
                                                                        at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:151)
                                                                        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
                                                                        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
                                                                        at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:318)
                                                                        at android.view.View.performClick(View.java:5610)
                                                                        at android.view.View$PerformClick.run(View.java:22260)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

`

### Do you have any ideas?

**Comment by fenjuly** [comment]
java.lang.ClassNotFoundException: Didn't find class "com.fenjuly.mylibrary.DropDownLayout" 
It looks like you were using gradle to include this project? Use  the project as a module instead.

**Comment by lidox** [comment]
ok thanks
